### ISSUE TITLE
Grad-only spin SHTs

### ISSUE THREAD

**Issue by mreineck** [mreineck/ducc#11]
I compared the `ALM2MAP_DERIV` SHT mode to the spin-SHTs, and as far as I can tell, it is identical to a spin-1 SHT where the curl component is zero, with one difference: the input `a_lm` are multiplied with an additional factor `sqrt(l*(l+1))`.

Does that agree with your observations, @carronj ?

If that is indeed the case (and if the transform works in an analogous fashion for higher spins), introducing grad-only `alm2map` and `adjoint_alm2map` should not be a big deal. In this mode I'd like to omit the `sqrt(l*(l+1))` factor however,and the user should apply it if needed.

**Comment by carronj** [comment]
All this  makes perfect sense to me.

**Comment by mreineck** [comment]
Implemented in 0.30
