### ISSUE TITLE
sharp: error on small map transforms with many threads 

### ISSUE THREAD

**Issue by samuelsimko** [mreineck/ducc#2]
The SHT transforms sometimes fail on small maps when the number of threads used is high.

### Steps to reproduce
Execute the following code :
``` {.py}
import ducc0
import numpy as np

nside = 4
mmax = nside
lmax = nside
nthreads = 10
nb_iter = 100

m = np.random.random(12 * nside ** 2)

job = ducc0.sht.sharpjob_d()
job.set_nthreads(nthreads)
job.set_healpix_geometry(nside=nside)
job.set_triangular_alm_info(lmax, mmax)
for _ in range(nb_iter):
    job.map2alm(m)
```

This code fails most of the time and throws this error on Linux Fedora 33:
```
/usr/include/c++/10/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = std::complex<double>; _Alloc = std::allocator<std::complex<double> >; std::vector<_Tp, _Alloc>::reference = std::complex<double>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
[1]    1044921 IOT instruction (core dumped)  python reproduce_ducc_err.py
```
On other operating systems, running the code can throw a segmentation fault instead.

**Comment by mreineck** [comment]
Thanks a lot! I'll investigate this as soon as possible.
Most likely this happens in threads which have nothing to do and nevertheless try doing it ...

**Comment by mreineck** [comment]
Which version of the code are you using exactly?

**Comment by samuelsimko** [comment]
0.9.0 (I installed it from the latest commit)

**Comment by mreineck** [comment]
Can you please try again with the latest commit? I fixed something which repairs the test case at least on my computer.

**Comment by samuelsimko** [comment]
The fix seems to work on my computer as well, I get no errors anymore.
Thank you !

**Comment by mreineck** [comment]
Great! Please re-open if the problem turns up again!
